name: Pull request on any branch
on:
  pull_request:
    branches:
      - main

jobs:
  Get-files-changed:
    uses: ./.github/workflows/files_changed.yaml
    with:
      folder_path: .*

  echo-output:
    name: echo output from files_changed
    runs-on: ubuntu-latest
    needs: Get-files-changed
    steps:
      - name: echo all changed files
        run: |
          echo ${{ needs.Get-files-changed.outputs.all_changed_files }} 
          echo boolean_output=${{ needs.Get-files-changed.outputs.boolean_output }}