name: Push on main branch
on:
  push:
    branches:
      - main

jobs:
  filesChanged:
    uses: ./.github/workflows/files_changed.yaml
    with:
      folder_path: .*


  echo-output:
    name: echo output from files_changed
    runs-on: ubuntu-latest
    needs: filesChanged
    steps:
      - name: echo all changed files
        run: |
          echo ${{ needs.filesChanged.outputs.all_changed_files }} 
          echo boolean_output=${{ needs.filesChanged.outputs.boolean_output }} 
